const express= require("express");
const cookieparser= require("cookie-parser");
const authRoutes=  require("./routes/auth.route");
const employeeRoutes= require("./routes/employee.route");
const adminRoutes= require("./routes/admin.route");
const app= express();
app.use(express.json());
app.use(cookieparser());
app.use("/api/auth",authRoutes);
app.use("/api/employee",employeeRoutes);
app.use("/api/admin",adminRoutes);
module.exports= app;